### ISSUE TITLE
Add Quick Sort in C

### ISSUE THREAD

**Issue by wileymab** [wileymab/project1531187128182#19]
See requirements: https://sample-programs.therenegadecoder.com/projects/quick-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c

**Comment by SwarajRenghe** [comment]
Initiated a pull request.

**Comment by wileymab** [comment]
Sorry, this was created for testing purposes. It is not an active issue. Please see this repo for the actual issue: https://github.com/TheRenegadeCoder/sample-programs
